apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.swagger.fullnameOverride }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
    {{- include "tcnp.labels.swagger" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "data-tool.selectorLabels" . | nindent 6 }}
      {{- include "tcnp.labels.swagger" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-tool.labels" . | nindent 8 }}
        {{- include "tcnp.labels.swagger" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "swaggerapi/swagger-ui"
          imagePullPolicy: {{ .Values.swagger.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: URLS
              value: "[ { url: \"https://{{ .Values.pgrest.ingress.host }}\", name: \"TCNP\" } ]"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 2
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.swagger.resources | nindent 12 }}
