apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-tool.fullname" . }}-swagger
  labels:
    app: dso-data-tool-swagger
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: dso-data-tool-swagger
  template:
    metadata:
      labels:
        app: dso-data-tool-swagger
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "swaggerapi/swagger-ui"
          imagePullPolicy: {{ .Values.swagger.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: URLS
              value: "[ { url: \"https://{{ .Values.pgrest.ingress.host }}\", name: \"Demo\" } ]"
          resources:
            {{- toYaml .Values.swagger.resources | nindent 12 }}
