apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.swagger.fullnameOverride }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
    {{- include "tcnp.labels.swagger" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "data-tool.selectorLabels" . | nindent 4 }}
    {{- include "tcnp.labels.swagger" . | nindent 4 }}