{{- if .Values.pgrest.ingress.enabled -}}
{{- $fullName := include "data-tool.fullname" . -}}
{{- $svcPort := .Values.pgrest.service.port -}}
{{- $adminPort := .Values.pgrest.admin.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
  {{- with .Values.pgrest.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.pgrest.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          - path: /live # 200 ok; 503 otherwise
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $adminPort }}
          - path: /ready # 200 ok; 503 otherwise
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $adminPort }}
          
{{- end }}