apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-tool.fullname" . }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.pgrest.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.pgrest.admin.port }}
      targetPort: httpAdmin
      protocol: TCP
      name: httpAdmin
  selector:
    {{- include "data-tool.selectorLabels" . | nindent 4 }}