apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.blackbox.name }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
data:
{{ (tpl (.Files.Glob "conf/blackbox/*").AsConfig .) | indent 2 }}
    