apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.blackbox.name }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
    app: tcnp-blackbox
spec:
  replicas: {{ .Values.blackbox.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "data-tool.selectorLabels" . | nindent 6 }}
      app: tcnp-blackbox
  template:
    metadata:
      labels:
        {{- include "data-tool.selectorLabels" . | nindent 8 }}
        app: tcnp-blackbox
        tier: monitoring
        env: {{ .Values.environnement }}
    spec:
      containers:
        - name: {{ .Values.blackbox.name }}
          image: "{{ .Values.blackbox.image.repository }}:{{ .Values.blackbox.image.tag }}"
          imagePullPolicy: {{ .Values.blackbox.image.pullPolicy }}
          ports:
            - name: "{{ .Values.blackbox.service.name }}"
              containerPort: {{ .Values.blackbox.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: "{{ .Values.blackbox.config.mountPath }}/blackbox.yml"
            - name: token-volume
              mountPath: "{{ .Values.blackbox.config.credentialPath }}"
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: "{{ .Values.blackbox.service.name }}"
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: "{{ .Values.blackbox.service.name }}"
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /-/healthy
              port: "{{ .Values.blackbox.service.name }}"
          resources:
            {{- toYaml .Values.blackbox.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.blackbox.name }}
        - name: token-volume
          secret:
            secretName: blackbox-exporter-token
