apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.blackbox.name }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
    {{- include "tcnp.labels.blackbox" . | nindent 4 }}
spec:
  replicas: {{ .Values.blackbox.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "data-tool.selectorLabels" . | nindent 6 }}
      {{- include "tcnp.labels.blackbox" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-tool.selectorLabels" . | nindent 8 }}
        {{- include "tcnp.labels.blackbox" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.blackbox.name }}
          image: "{{ .Values.blackbox.image.repository }}:{{ .Values.blackbox.image.tag }}"
          imagePullPolicy: {{ .Values.blackbox.image.pullPolicy }}
          args: ["--config.file", "{{ .Values.blackbox.config.mountPath }}/config.yml"]
          ports:
            - name: "{{ .Values.blackbox.service.name }}"
              containerPort: {{ .Values.blackbox.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: "{{ .Values.blackbox.config.mountPath }}"
            - name: token-volume
              mountPath: "{{ .Values.blackbox.config.credentialPath }}"
          readinessProbe:
            httpGet:
              path: /-/healthy
              port: "{{ .Values.blackbox.service.name }}"
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: "{{ .Values.blackbox.service.name }}"
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /-/healthy
              port: "{{ .Values.blackbox.service.name }}"
          resources:
            {{- toYaml .Values.blackbox.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.blackbox.name }}
        - name: token-volume
          secret:
            secretName: blackbox-exporter-token
