apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.blackbox.name }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
    tier: monitoring
    composant: prometheus-blackbox
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.blackbox.service.port }}
      targetPort: {{ .Values.blackbox.service.name }}
      protocol: TCP
      name: {{ .Values.blackbox.service.name }}
  selector:
    {{- include "data-tool.selectorLabels" . | nindent 4 }}
    tier: monitoring
    composant: prometheus-blackbox