apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.blackbox.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "data-tool.labels" . | nindent 4 }}
    {{- include "tcnp.labels.blackbox" . | nindent 6 }}
spec:
  endpoints:
  - port: "{{ .Values.blackbox.service.name }}"
    scheme: "http"
    path: "/probe"
    interval: "30s"
    scrapeTimeout: "30s"
    params:
      module:
      - "http_2xx"
      target:
      - "http://{{ include "data-tool.fullname" . }}:{{ .Values.pgrest.admin.port }}/live"
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: "http://{{ include "data-tool.fullname" . }}:{{ .Values.pgrest.admin.port }}/live"
        action: replace
      - sourceLabels: [target]
        targetLabel: target
        replacement: "pgrest-live"
        action: replace
  - port: "{{ .Values.blackbox.service.name }}"
    scheme: "http"
    path: "/probe"
    interval: "30s"
    scrapeTimeout: "30s"
    params:
      module:
      - "http_2xx"
      target:
      - "http://{{ include "data-tool.fullname" . }}:{{ .Values.pgrest.admin.port }}/ready"
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: "http://{{ include "data-tool.fullname" . }}:{{ .Values.pgrest.admin.port }}/ready"
        action: replace
      - sourceLabels: [target]
        targetLabel: target
        replacement: "pgrest-ready"
        action: replace
  - port: "{{ .Values.blackbox.service.name }}"
    scheme: "http"
    path: "/probe"
    interval: "30s"
    scrapeTimeout: "30s"
    params:
      module:
      - "http_2xx_with_auth"
      target:
      - "http://{{ include "data-tool.fullname" . }}:{{ .Values.pgrest.service.port }}/identites?prenoms_officiels_q=ilike.Astérix&limit=10"
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: "http://{{ include "data-tool.fullname" . }}:{{ .Values.pgrest.service.port }}/identites?prenoms_officiels_q=ilike.Astérix&limit=10"
        action: replace
      - sourceLabels: [target]
        targetLabel: target
        replacement: "pgrest-request-valid"
        action: replace
  - port: "{{ .Values.blackbox.service.name }}"
    scheme: "http"
    path: "/probe"
    interval: "30s"
    scrapeTimeout: "30s"
    params:
      module:
      - "http_4xx_no_auth"
      target:
      - "http://{{ include "data-tool.fullname" . }}:{{ .Values.pgrest.service.port }}/identites?prenoms_officiels_q=ilike.Astérix&limit=10"
    metricRelabelings:
      - sourceLabels: [instance]
        targetLabel: instance
        replacement: "http://{{ include "data-tool.fullname" . }}:{{ .Values.pgrest.service.port }}/identites?prenoms_officiels_q=ilike.Astérix&limit=10"
        action: replace
      - sourceLabels: [target]
        targetLabel: target
        replacement: "pgrest-request-no-auth"
        action: replace

  selector:
    matchLabels:
      {{- include "data-tool.selectorLabels" . | nindent 6 }}
      {{- include "tcnp.labels.blackbox" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
